# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A multi-prob calculator for Deliveryman Assignment Problem
#' @description A multi-prob calculator using Rcpp
#' @param x the probability vector of each deliveryman
#' @param target there are excatly target number of deliverymen take order
#' @param n the length of vector x
#' @return the objective probability
#' @examples
#' \dontrun{
#' prob <- c(0.5, 0.5, 0.5, 0.5, 0.5)
#' target <- 1
#' n <- 5
#' DAP(prob, target, n)
#' }
#' @importFrom Rcpp evalCpp
#' @export
DAP <- function(x, target, n) {
    .Call('_SA23204185_DAP', PACKAGE = 'SA23204185', x, target, n)
}

